version: '3.8'

services:
  api:
    build: .
    container_name: feedback-api
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./prisma:/app/prisma
    command: sh -c "npx prisma generate && npm run build && node dist/index.js"
