version: "3.8"

services:
  api:
    build: .
    container_name: feedback-api
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - feedback-db:/app/prisma/prisma/dev.db
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run build && node dist/index.js"

volumes:
  feedback-db:
